function adminGnb(){
	return '<div>'
	+   '<ul class="kal-gg-gnb">'
	+   '<li class="kal-gg-gnb-li">ADMIN</li>'
	+   '<li class="kal-gg-gnb-hover" id="kal-gg-gnb-gotoAdmin">MAIN</li>'
	+   '<li class="kal-gg-gnb-hover" id="kal-gg-gnb-gotomain">HOMEPAGE</li>'
	+   '<li class="kal-gg-gnb-hover">SNS</li>'
	+   '<li class="kal-gg-gnb-hover">SETTING</li>'
	+   '<li class="kal-gg-gnb-hover" id="kal-gg-gnb-logout">LOGOUT</li>'
	+   '</ul>'
	+   '</div>';
}

function adminNav(){
	return '<div class="kal-gg-body">'
	+ '<div class="kal-gg-nav">'
	+   '<div id="kal-gg-nav-user" class="kal-gg-nav-img">'
	+   	 '<img src="'+$.context()+'/resources/img/admin/nav/user1.jpg" id="navUser">'
	+   '</div>'
	+   '<div id="kal-gg-nav-res" class="kal-gg-nav-img">'
	+ 	 '<img src="'+$.context()+'/resources/img/admin/nav/res1.jpg" id="navRes">' 
	+  '</div>'
	+   '<div id="kal-gg-nav-sche" class="kal-gg-nav-img">'
	+ 	  '<img src="'+$.context()+'/resources/img/admin/nav/sche1.jpg" id="navSche">'
	+   '</div>'
	+   '<div id="kal-gg-nav-board" class="kal-gg-nav-img">'
	+ 	  '<img src="'+$.context()+'/resources/img/admin/nav/board1.jpg" id="navBoard">' 
	+   '</div>'
	+   '<div id="kal-gg-nav-flight" class="kal-gg-nav-img">'
	+ 	 '<img src="'+$.context()+'/resources/img/admin/nav/flight1.jpg" id="navFlight">' 
	+   '</div>'
	+   '<div id="kal-gg-nav-route" class="kal-gg-nav-img">'
	+ 	 '<img src="'+$.context()+'/resources/img/admin/nav/route1.jpg" id="navRoute">'
	+   '</div>'
	+   '<div id="kal-gg-nav-stat" class="kal-gg-nav-img">'
	+ 	 '<img src="'+$.context()+'/resources/img/admin/nav/stat1.jpg" id="navStat">'
	+   '</div>'
	+  		'<div class="kal-gg-nav-drop" id="kal-gg-nav-drop-con">CONNECTION</div>'
	+ 		'<div class="kal-gg-nav-drop" id="kal-gg-nav-drop-user">USER</div>'
	+ 		'<div class="kal-gg-nav-drop" id="kal-gg-nav-drop-res">RESERVATION</div>'
	+ 		'<div class="kal-gg-nav-drop" id="kal-gg-nav-drop-searching">SEARCHING</div>'
	+ 		'<div class="kal-gg-nav-drop" id="kal-gg-nav-drop-sales">SALES</div>'
	+ '</div>'
	+ '<div id="admin-wrapper"></div>';
}



function createPopupForm(){
	return '<div class="kal-gg-white-popup">'
    +         '<div><img src="'+$.context()+'/resources/img/reservation/koreanAirLogo.png" alt=""></a></div>'
    +         '<div class="kal-gg-admin-box">'
    +       '<h1 style="color:#0180a3;">WELCOM ADMIN</h1>'
	+	'<div class="form-group">'
	+       '<label for="text"></label>'
	+		'<input type="text" class="kal-gg-form-control" id="code" placeholder="Access Code">'
	+	'</div>'
    +   '<div class="form-group">'
	+		'<label for="pwd"></label>'
	+		'<input type="password" class="kal-gg-form-control" id="pass" placeholder="Password">'
    +   '</div>'
    +	'<button id="adminLogin" class="kal-gg-btn">Login</button>'
    +   '</div>'
	+'</div>';
}


function reserCon(){
	return '<div id="kal-gg-reser-con-wrapper" class="kal-gg-reser-con">'
	+     	 '<div id="kal-gg-reser-con-wrapper2" class="kal-gg-reser-con2">'
    +	   		'<div class="kal-gg-reser-inner-con">'
	+    		'<div class="kal-gg-reser-con-title">'
	+    		'<h2>RESERVATION</h2>'
	+    		'</div>'
    +		'<div>'
    +			'<div class="kal-gg-reser-con-subtitle">'
    +			'<h3 >SEARCH RESERVATION</h3> '
    +			'</div>'
    +			'<table class="kal-gg-reser-con-table">'
    +				'<tr >'
    +					'<th>DATE</th>'
    +					'<th>ROUTE FROM</th>'
    +					'<th>ROUTE TO</th>'
    +					'<th>USER ID</th>'
    +				'</tr>'
    +				'<tr>'
    +					'<td><input type="text" id="kal-gg-reser-date"></td>'
    +					'<td><input type="text" id="kal-gg-reser-departure"/></td>'
    +					'<td><input type="text" id="kal-gg-reser-destination"/></td>'
    +					'<td><input type="text" id="kal-gg-reser-userId"/></td>'
    +				'</tr>'
    +			'</table>'
    +				'<button class="kal-gg-reser-con-btn" id="kal-gg-reser-createBtn">search</button>	'
    +		'</div>'
    +		'<div>'
    +			'<div class="kal-gg-reser-con-wrapper">'
    +			   '<div class="kal-gg-reser-con-table-wrapper">'
    +					'<div id="reserListWrapper" class="kal-gg-reser-empty">'
    +                   '</div>'
    +					 '<div id="reserUpdateDeleteBtnWrapper">'
    +					'</div>'
    +		'<div class="kal-gg-reser-con-btm"></div>'
    +				 '</div>'
    +				 '</div>'
    +		'</div>'
    +	      '</div>'
    +	     '</div>'
    +		'</div>';

}




function scheCon(){
	return '<div id="kal-gg-sche-con-wrapper" class="kal-gg-sche-con">'
	+     	 '<div class="kal-gg-sche-con2">'
    +	   	'<div class="kal-gg-sche-inner-con">'
	+    		'<div class="kal-gg-sche-con-title">'
	+    		'<h2>SCHEDULE</h2>'
	+    		'</div>'
    +		'<div>'
    +			'<div class="kal-gg-sche-con-subtitle">'
    +			'<h3 >CREATE SCHEDULE</h3> '
    +			'</div>'
    +			'<p class="kal-gg-sche-table-text"></p>'
    +			'<table class="kal-gg-sche-con-table">'
    +				'<tr >'
    +					'<th>ROUTE NO</th>'
    +					'<th>DATE</th>'
    +					'<th>DEPARTURE TIME</th>'
    +					'<th>DESTINATION TIME</th>'
    +				'</tr>'
    +				'<tr>'
    +					'<td>'
    +						'<select class="kal-gg-sch-con-select" id="kal-gg-sch-createSelect">' 
    +						'<option value="1">1.ICN-HND</option>'
    +						'<option value="2">2.JFK-JFK</option>'
    +						'<option value="3">3.HND-ICN</option>'
    +						'<option value="4">4.HND-JFK</option>'
    +						'<option value="5">5.JFK-ICN</option>'
    +						'<option value="6">6.JFK-HND</option>'
    +						'<option value="7">7.HND-ICN</option>'
    +						'<option value="8">8.JFK-ICN</option>'
    +						'<option value="9">9.ICN-HND</option>'
    +						'<option value="10">10.JFK-HND</option>'
    +						'<option value="11">11.ICN-JFK</option>'
    +						'<option value="12">12.HND-JFK</option></select>'
    +					'</td>'
    +					'<td><input type="text" id="kal-gg-sch-date"/></td>'
    +					'<td><input type="text" id="kal-gg-sch-departureTime"/></td>'
    +					'<td><input type="text" id="kal-gg-sch-destinationTime"/></td>'
    +				'</tr>'
    +			'</table>'
    +				'<button class="kal-gg-sche-con-btn" id="kal-gg-sche-createBtn">CREATE</button>	'
    +		'</div>'
    +		'<div>'
    +			'<div>'
    +				'<div class="kal-gg-sche-con-subtitle">'
    +					'<h3>SEARCH SCHEDULE</h3> '
    +				'</div>'
    +				'<div class="kal-gg-sche-con-search">'
    +					'<div>'
    +						'DATE:<input type="text" value="" id="gg-searchDate"/>'
    +					'</div>'
    +					'<div>'
    +						'DEPARTURE:<input type="text" value="" id="gg-departure"/>'
    +					'</div>'
    +					'<div>'
    +						'DESTINATION:<input type="text" value="" id="gg-destination" /><br />'	
    +					'</div>'
    +				'</div>'
    +				'<div><input type="button" value="search" class="kal-gg-sche-searchBtn" id="kal-gg-serchBtn"/></div>'
    +				'<div class="kal-gg-sche-con-search-cal">'
    +				'</div>'
    +			'</div>'
    +			'<div class="kal-gg-sche-con-wrapper">'
    +			'<div class="kal-gg-sche-con-table-wrapper">'
    +					'<div id="scheListWrapper">'
    +                   '</div>'
    +					 '<div id="scheUpdateDeleteBtnWrapper">'
    +					'</div>'
    +				 '</div>'
    +				 '</div>'
    +			'</div>'
    +		      '<div id="updateWrapper">'
    +		      '</div>'
    +	      '</div>'
    +	     '</div>'
	+			'<div class="kal-gg-sche-con-btm">'
	+			'</div>'
    +		'</div>';
}
function scheUpdateCon(){
	return '<div class="kal-gg-sche-con-subtitle">'
	+			  '<h3 >UPDATE SCHEDULE</h3>' 
	+			   '<div id="scheUpdateTable"></div>'
	+			'<div>'
	+				'<button class="kal-gg-sche-con-btn" id="scheUpdateConfirm">update</button>'
	+			'</div>'
	+		'</div>';
}

function routeCon(){
	return '<div id="wrapper" class="kal-gg-route-con">'
+     	 '<div class="kal-gg-route-con2">'
+		'<div class="kal-gg-route-inner-con">'
+		'<div class="kal-gg-route-con-title">'
+			'<h2>ROUTE</h2>'
+		'</div>'
+		'<div>'
+			'<div class="kal-gg-route-con-subtitle">'
+			'<h3 >CREATE ROUTE</h3> '
+			'</div>'
+			'<table class="kal-gg-route-con-table">'
+				'<tr >'
+					'<th>FLIGHT NO</th>'
+					'<th>DEPARTURE</th>'
+					'<th>DESTINATION </th>'
+				'</tr>'
+				'<tr>'
+					'<td><select name="" id="" class="kal-gg-route-con-select">'
+						'<option value="1">1.boeing 777-200ER</option>'
+						'<option value="2">2.boeing 777-200ER</option>'
+						'<option value="3">3.boeing 777-200ER</option>'
+						'<option value="4">4.boeing 777-200ER</option>'
+						'<option value="5">5.boeing 777-200ER</option>'
+						'<option value="6">6.boeing 777-200ER</option>'
+						'<option value="7">7.boeing 777-200ER</option>'
+					'</select></td>'
+					'<td><input type="text" id="RouteDepartureInput"/></td>'
+					'<td><input type="text" id="RouteArrInput"/></td>'
+			'</tr>'
+			'</table>'
+			'<button class="kal-gg-route-con-createBtn">CREATE</button>'
+		'</div>'
+		'<div>'
+			'<div>'
+				'<div class="kal-gg-route-con-subtitle">'
+					'<h3>SEARCH ROUTE</h3> '
+				'</div>	'
+				'<div class="kal-gg-route-con-search">'
+					'<div>'
+						'FLIGHT NO:<input type="text" id="routeFlightSerch" value=""/>'
+					'</div>'
+					'<div>'
+						'DEPARTURE:<input type="text" id="routeDepartSerch" value=""/>'
+					'</div>'
+					'<div>'
+						'DESTINATION:<input type="text" id="routeDesSerch"  value=""/>'	
+					'</div>'
+				'</div><div><button  id="routeSerchBtn" class="kal-gg-route-searchBtn">search</button>'
+				'<div class="kal-gg-route-con-search-cal">'
+				'</div>'
+			'</div>'
+			'<div>'
+				'<div id="routeListWrapper"></div>'
+			'</div>'
+		'<div id="routeBtnWrapper"></div>'
+		'<div id="routeUpdateWrapper"></div>'
+		'</div>'
+		'</div>'
+		'</div>'
+		'</div>'
+			'<div class="kal-gg-route-con-btm">'
+			'</div>'
+		'</div>'
+		'</div>';
}
function routeConUpdate(){
	return '<div class="kal-gg-route-con-subtitle">'
	+			  '<h3 >UPDATE ROUTE</h3> '
	+				'<div id="routeUpdateTable"></div>'
	+			'<div>'
	+				'<button class="kal-gg-route-con-btn" id="routeUpdateConfirm">update</button>'
	+			'</div>';
}
function homeCon(){
 return 
 '<div class="kal-gg-stat-con">'
+ '<div id="piechart" class="kal-gg-stat-chart"></div>'
+ '<div id="sexchart" class="kal-gg-stat-chart"></div>'
+ '</div>'
+ '</div>';
}

function flightCon(){
 return '<div id="wrapper" class="kal-gg-flight-con">'
+	' <div class="kal-gg-flight-inner-con">'
+	' <div class="kal-gg-flight-con-title">'
+	 	'<h2>FLIGHT</h2>'
+	 '</div>'
+	 '<div>'
+	 	'<div class="kal-gg-flight-con-subtitle">'
+	 	'<h3 >CREATE FLIGHT</h3>' 
+	 	'</div>'
+	 	'<table class="kal-gg-flight-con-table">'
+	 		'<tr >'
+	 			'<th>FLIGHT NAME</th>'
+	 			'<th>FLIGHT TYPE</th>'
+	 			'<th>SEAT COUNT</th>'
+	 		'</tr>'
+	 		'<tr>'
+	 			'<td>KOREAN AIR</td>'
+	 			'<td><input type="text"/></td>'
+	 			'<td><input type="text"/></td>'
+	 	'</tr>'
+	 	'</table>'
+	 	'<button class="kal-gg-flight-con-btn">CREATE</button>'
+	 '</div>'
+	 '<div>'
+	 	'<div>'
+	 		'<div class="kal-gg-flight-con-subtitle">'
+	 			'<h3>SEARCH FLIGHT</h3> '
+	 		'</div>'	
+	 		'<div class="kal-gg-flight-con-search">'
+	 			'<div>'
+	 				'FLIGHT TYPE:<input type="text" value=""/><input type="button" value="search"/>'
+	 			'</div>'
+	 			'<div>'
+	 				'SEAT COUNT:<input type="text" value="" /><input type="button" value="search"/><br />'	
+	 			'</div>'
+	 		'</div>'
+	 		'<div class="kal-gg-flight-con-search-cal">'
+	 		'</div>'
+	 	'</div>'
+	 	'<div>'
+	 		'<div>'
+	 			'<table class="kal-gg-flight-con-table2">'
+	 			'<tr >'
+	 				'<th>FLIGHT NAME</th>'
+	 				'<th>FLIGHT TYPE</th>'
+	 				'<th>SEAT COUNT</th>'	
+	 			'</tr>'
+	 			'<tr>'
+	 				'<td> KOREAN AIR</td>'
+	 				'<td>1</td>'
+	 				'<td>2</td>'
+	 			'</tr>'
+	 			'<tr>'
+	 				'<td> KOREAN AIR</td>'
+	 				'<td>1</td>'
+	 				'<td>4</td>'
+	 			'</tr>'
+	 			'<tr>'
+	 				'<td> KOREAN AIR</td>'
+	 				'<td>1</td>'
+	 				'<td>5</td>'
+	 			'</tr>'
+	 			'<tr>'
+	 				'<td> KOREAN AIR</td>'
+	 				'<td>1</td>'
+	 				'<td>6</td>'
+	 			'</tr>'
+	 			 '</table>'
+	 			' <div>'
+	 			 		'<div class="kal-gg-flight-con-btn-add">'
+	 					  '<button class="kal-gg-flight-con-btn">delete</button>'
+	 					  '<button class="kal-gg-flight-con-btn">update</button>'
+	 				 	'</div>'
+	 				 	'<div class="kal-gg-flight-con-btn-add">'
+	 					 ' <button class="kal-gg-flight-con-btn">delete</button>'
+	 					  '<button class="kal-gg-flight-con-btn">update</button>'
+	 				 	'</div>'
+	 				 	'<div class="kal-gg-flight-con-btn-add">'
+	 					 ' <button class="kal-gg-flight-con-btn">delete</button>'
+	 					 ' <button class="kal-gg-flight-con-btn">update</button>'
+	 				 	'</div>'
+	 				 '	<div class="kal-gg-flight-con-btn-add">'
+	 					  '<button class="kal-gg-flight-con-btn">delete</button>'
+	 					  '<button class="kal-gg-flight-con-btn">update</button>'
+	 				 	'</div>'
+	 			' </div>'
+	 		'</div>'
+	 '</div>'
+	 	 ' <div class="kal-gg-flight-con-subtitle">'
+	 	 ' <h3 >UPDATE FLIGHT</h3> '
+	 	'<table class="kal-gg-flight-con-table">'
+	 		'<tr >'
+	 			'<th>FLIGHT NAME</th>'
+	 			'<th>FLIGHT TYPE</th>'
+	 			'<th>SEAT COUNT</th>'	
+	 		'</tr>'
+	 		'<tr >'
+	 			'<td>KOREAN AIR</td>'
+	 			'<td>boeing 777-200ER</td>'
+	 			'<td>76</td>'
+	 		'</tr>	'
+	 	   '<tr>'
+	 			'<td>KOREAN AIR</td>'
+	 			'<td><input type="text" /></td>'
+	 			'<td><input type="text" /></td>'
+	 		'</tr>'
+	 	'</table>'
+	    '<div>'
+	 		'<button id="update" class="kal-gg-flight-con-btn">update</button>'
+	 	'</div>'
+	 	'<div class="kal-gg-flight-con-btm">'
+	 	'</div>'
+	 '</div>'
+	 '</div>'
+	 '</div>'
+	 '</div>';
}



function googleChart(){
	return '<div class="kal-gg-stat-con">'
+'	  <div class="kal-gg-chart-line" >'
+'	   <h1>SALES CHART</h1>'
+'	  </div>'
+'	  <div class="kal-gg-chart-div">'
+'	     <div class="kal-gg-chart-innerDiv">'
+'	     	<div class="kal-gg-chart-calendar">'
+'	        조회기간'
+'		         <input type="text" id="datepicker1" calss="kal-gg-chart-calendar"> ~'
+'		         <input type="text" id="datepicker2" calss="kal-gg-chart-calendar">'
+'            </div>'
+'            <select name="" id="" class="kal-gg-selectbox">'
+'                 <option value="sche_date">총 매출 </option>'
+'                 <option value="user_gen">성 별</option>'
+'                 <option value="birth_date">연령 별</option>'
+'                 <option value="route_from,route_to">행선지 별</option>'
+'	        </select>'
+'            <input type="button" value="search" class="kal-gg-chart-btn 1" id="kal-gg-chart-search">' 
+'            <div class="kal-gg-chart-result" id="kal-gg-chart-wrapper">'
+'	        </div>' 
+'	        </div>'
+'	      </div>'
+'	   </div>';
}
