function boardFAQlist(){
            return  '<div id="kal-faq-ss-img" class="kal-faq-ss-bg">'
            +'<div class="kal-faq-ss-title">'
            +'<h2>FAQ</h2>'
            +'</div>'
            +'<div id="wrapper" class="kal-faq-ss-wrapper">'
            +'<div class="kal-faq-ss-h2">'
            +'답변보기'
            +'</div>'
            +'<div class="kal-faq-ss">'
            +'<div class="kal-faq-ss-form">'
            +'<div class="kal-faq-ss-formstyle">'
            +'<div class="kal-faq-ss-align">'
                +'<label for="kal-qna-ss-select" class="kal-faq-ss-label">상위분류</label>'
                    +'<select name="" id="kal-qna-ss-select" class="kal-faq-ss-select-style">'
                        +'<option value="전체">전체</option>'
                        +'<option value="항공권 예약/구매/환불">항공권 예약/구매/환불</option>'
                        +'<option value="스카이패스">스카이패스</option>'
                        +'<option value="홈페이지 이용">홈페이지 이용</option>'
                        +'<option value="공항 서비스">공항 서비스</option>'
                        +'<option value="수하물 관련">수하물 관련</option>'
                        +'<option value="객실 서비스">예매</option>'
                        +'<option value="기내식">객실 서비스</option>'
                        +'<option value="제휴 항공사">제휴 항공사</option>'
                        +'<option value="기타">기타</option>'
                    +'</select>'
                    +'</div>'
                    +'</div>'
                    +'<button class="kal-search-ss-button">검색'
                    +'<span class="kal-search-ss-button-image"></span>'
                    +'</button>'
                +'<div class="kal-search-ss-contanier">'
                +'<div class="kal-faq-ss-bar"></div>'
                +'<div>'
                +'<label for="faq-search" class="kal-faq-ss-searchlabel">FAQ 검색하기</label>'
                +'<span class="kal-faq-ss-holder" id="faq-search"></span>'
                +'<input type="text"  class="kal-faq-ss-search" aria-describedby="faq-search" placeholder="수하물,스카이패스 등"/>'
                +'</div>'           
            +'<button class="kal-search-ss-button-submit"></button>'
            +'</div>'
            +'</div>'
            +'<div class="kal-ss-faq-btnAll-style">'
                +'<button id="kal-all-ss-button" class="kal-search-ss-button-all">답변보기'
                +'<span></span>'   
                +'</button>'
                +'</div>'
                +'<ul class="kal-result-ss-count">'
                +'<li>전체'
                +'<span class="kal-result-ss-before"></span>'
                +'</li>'
                +'<li>전체</li>'
                +'<li>(5)</li>'
                +'</ul>'
                +'<div id="kal-faq-ss-container" class="kal-faq-ss-list-border">'
                +'<ul class=" kal-list-ss-ul">'
                +'<li class="kal-list-ss-li">'
                +'<a href="javascript:void(0);" id="kal-faqList-a">'
                +'Q1. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
                +'<span class="kal-list-ss-plus"></span>'
                +'</a>'
                +'<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
                +'<div>'
                +'<span>A:</span>'
                +'<span class="kal-list-ss-ans">Answer</span>'
                    +'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
                    +'</div>'
                +'</div>'
            +'</li>'
            +'<li class="kal-list-ss-li">'
                +'<a href="javascript:void(0);" id="kal-faqList-a1">'
                +'Q2. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
                +'<span class="kal-list-ss-plus"></span>'
                +'</a>'
                +'<div id="kal-faq-ss-answer1" class="kal-list-ss-answer">'
                +'<div tabindex="-1">'
                +'<span>A:</span>'
                +'<span class="kal-list-ss-ans">Answer</span>'
                    +'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
                    +'</div>'
                +'</div>'
            +'</li>'
            +'<li class="kal-list-ss-li">'
            +'<a href="javascript:void(0);" id="kal-faqList-a2" tabindex="-1">'
                +'Q3. : 실시간 계좌이체로 다른 사람의 항공권을 구매할 수 있나요?'
                +'<span class="kal-list-ss-plus"></span>'
                +'</a>'
                +'<div id="kal-faq-ss-answer2" class="kal-list-ss-answer">'
                    +'<div tabindex="-1">'
                    +'<span>A:</span>'
                    +'<span class="kal-list-ss-ans">Answer</span>'
                    +'<p>예금주와 공인인증서 소지자가 동일한 경우 계좌이체로 항공권을 구매할 수 있습니다. 다른 사람의 항공권 구매도 가능합니다. </p>'
                    +'</div>'
                +'</div>'
            +'</li>'
            +'<li class="kal-list-ss-li">'
            +'<a href="javascript:void(0);" id="kal-faqList-a3" tabindex="-1">'
            +'Q4. : 안전결제(ISP)/안심클릭 서비스 신청은 어떻게 하나요?'
                +'<span class="kal-list-ss-plus"></span>'
                +'</a>'
                +'<div id="kal-faq-ss-answer3" class="kal-list-ss-answer">'
                +'<div tabindex="-1">'
                +'<span>A:</span>'
                +'<span class="kal-list-ss-ans">Answer</span>'
                    +'<p>신용카드사 홈페이지 또는 결제창에서 안전결제(ISP)/안심클릭 서비스를 신청할 수 있습니다.  </p>'
                    +'</div>'
                +'</div>'
            +'</li>'
            +'<li class="kal-list-ss-li">'
                +'<a href="javascript:void(0);" id="kal-faqList-a4">'
                +'Q5. : 아이디를 변경하고 싶습니다.'
                +'<span class="kal-list-ss-plus"></span>'
                +'</a>'
                +'<div id="kal-faq-ss-answer4" class="kal-list-ss-answer">'
                +'<div>'
                +'<span>A:</span>'
                +'<span class="kal-list-ss-ans">Answer</span>'
                    +'<p>인터넷 회원으로 가입하셨을 때 등록하신 아이디는 다른 아이디로 변경아이디 변경을 원하실 경우, 불편하시더라도 인터넷 회원 탈퇴를 하신 후 재가입하시기 바랍니다                          </p>'
                    +'</div>'
                +'</div>'
                +'</div>'
                +'</div>'
                +'</div>';
        }